<?php

namespace Kernl\Lib;

use StoutLogic\AcfBuilder\FieldsBuilder;

class Acf
{
    // kernl(ui) icon names
    public static $icons = ['activity', 'airplay', 'alert-circle', 'alert-octagon', 'alert-triangle', 'align-center', 'align-justify', 'align-left', 'align-right', 'anchor', 'aperture', 'archive', 'arrow-down-circle', 'arrow-down-left', 'arrow-down-right', 'arrow-down', 'arrow-left-circle', 'arrow-left', 'arrow-right-circle', 'arrow-right', 'arrow-up-circle', 'arrow-up-left', 'arrow-up-right', 'arrow-up', 'at-sign', 'award', 'bar-chart-2', 'bar-chart', 'battery-charging', 'battery', 'bell-off', 'bell', 'bluetooth', 'bold', 'book-open', 'book', 'bookmark', 'box', 'briefcase', 'calendar', 'camera-off', 'camera', 'cast', 'check-circle', 'check-square', 'check', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'chevrons-down', 'chevrons-left', 'chevrons-right', 'chevrons-up', 'chrome', 'circle', 'clipboard', 'clock', 'cloud-drizzle', 'cloud-lightning', 'cloud-off', 'cloud-rain', 'cloud-snow', 'cloud', 'code', 'codepen', 'command', 'compass', 'copy', 'corner-down-left', 'corner-down-right', 'corner-left-down', 'corner-left-up', 'corner-right-down', 'corner-right-up', 'corner-up-left', 'corner-up-right', 'cpu', 'credit-card', 'crop', 'crosshair', 'database', 'delete', 'disc', 'dollar-sign', 'download-cloud', 'download', 'droplet', 'edit-2', 'edit-3', 'edit', 'external-link', 'eye-off', 'eye', 'facebook', 'fast-forward', 'feather', 'file-minus', 'file-plus', 'file-text', 'file', 'film', 'filter', 'flag', 'folder-minus', 'folder-plus', 'folder', 'gift', 'git-branch', 'git-commit', 'git-merge', 'git-pull-request', 'github', 'gitlab', 'globe', 'grid', 'hard-drive', 'hash', 'headphones', 'heart', 'help-circle', 'home', 'image', 'inbox', 'info', 'instagram', 'italic', 'layers', 'layout', 'life-buoy', 'link-2', 'link', 'linkedin', 'list', 'loader', 'lock', 'log-in', 'log-out', 'mail', 'map-pin', 'map', 'maximize-2', 'maximize', 'menu', 'message-circle', 'message-square', 'mic-off', 'mic', 'minimize-2', 'minimize', 'minus-circle', 'minus-square', 'minus', 'monitor', 'moon', 'more-horizontal', 'more-vertical', 'move', 'music', 'navigation-2', 'navigation', 'octagon', 'package', 'paperclip', 'pause-circle', 'pause', 'percent', 'phone-call', 'phone-forwarded', 'phone-incoming', 'phone-missed', 'phone-off', 'phone-outgoing', 'phone', 'pie-chart', 'play-circle', 'play', 'plus-circle', 'plus-square', 'plus', 'pocket', 'power', 'printer', 'radio', 'refresh-ccw', 'refresh-cw', 'repeat', 'rewind', 'rotate-ccw', 'rotate-cw', 'rss', 'save', 'scissors', 'search', 'send', 'server', 'settings', 'share-2', 'share', 'shield-off', 'shield', 'shopping-bag', 'shopping-cart', 'shuffle', 'sidebar', 'skip-back', 'skip-forward', 'slack', 'slash', 'sliders', 'smartphone', 'speaker', 'square', 'star', 'stop-circle', 'sun', 'sunrise', 'sunset', 'tablet', 'tag', 'target', 'terminal', 'thermometer', 'thumbs-down', 'thumbs-up', 'toggle-left', 'toggle-right', 'trash-2', 'trash', 'trending-down', 'trending-up', 'triangle', 'truck', 'tv', 'twitter', 'type', 'umbrella', 'underline', 'unlock', 'upload-cloud', 'upload', 'user-check', 'user-minus', 'user-plus', 'user-x', 'user', 'users', 'video-off', 'video', 'voicemail', 'volume-1', 'volume-2', 'volume-x', 'volume', 'watch', 'wifi-off', 'wifi', 'wind', 'x-circle', 'x-square', 'x', 'youtube', 'zap-off', 'zap', 'zoom-in', 'zoom-out'];

    // "Block" options, mapped from kernl(ui)
    public static $options = [
        'accordion' => [
            ['-white' =>  'White'],
            ['-dark' =>   'Dark'],
            ['-spaced' =>   'Spaced'],
        ],
        'button' => [
            ['-lg' => 'Large'],
            ['-m' => 'Red underline'],
            ['-block' => 'Block (full width)'],
        ],
        'card' => [
            ['-tile' => 'Tile'],
            ['-h' => 'Horizontal'],
            ['-h@t' => 'Horizontal @t'],
            ['-h@d' => 'Horizontal @d'],
            ['-h@w' => 'Horizontal @w'],
            ['+avatar' => 'Has Avatar'],
            ['-overlay' => 'Overlay'],
            ['-middle' => 'Align middle'],
            ['-bottom' => 'Align bottom'],
        ],
        'column' => [
            ['measure'   => 'width: measure'],
            ['measure-narrow' => 'width: measure narrow'],
            ['measure-wide' => 'width: measure wide'],
            ['w-auto'   => 'width: auto'],
            ['w-auto@t' => 'width: auto@t'],
            ['w-auto@d' => 'width: auto@d'],
            ['w-auto@w' => 'width: auto@w'],
            ['w-fit'    => 'width: fit'],
            ['w-fit@t'  => 'width: fit@t'],
            ['w-fit@d'  => 'width: fit@d'],
            ['w-fit@w'  => 'width: fit@w'],
            ['w-10'     => 'width: 10'],
            ['w-10@t'   => 'width: 10@t'],
            ['w-10@d'   => 'width: 10@d'],
            ['w-10@w'   => 'width: 10@w'],
            ['w-20'     => 'width: 20'],
            ['w-20@t'   => 'width: 20@t'],
            ['w-20@d'   => 'width: 20@d'],
            ['w-20@w'   => 'width: 20@w'],
            ['w-25'     => 'width: 25'],
            ['w-25@t'   => 'width: 25@t'],
            ['w-25@d'   => 'width: 25@d'],
            ['w-25@w'   => 'width: 25@w'],
            ['w-30'     => 'width: 30'],
            ['w-30@t'   => 'width: 30@t'],
            ['w-30@d'   => 'width: 30@d'],
            ['w-30@w'   => 'width: 30@w'],
            ['w-40'     => 'width: 40'],
            ['w-40@t'   => 'width: 40@t'],
            ['w-40@d'   => 'width: 40@d'],
            ['w-40@w'   => 'width: 40@w'],
            ['w-50'     => 'width: 50'],
            ['w-50@t'   => 'width: 50@t'],
            ['w-50@d'   => 'width: 50@d'],
            ['w-50@w'   => 'width: 50@w'],
            ['w-60'     => 'width: 60'],
            ['w-60@t'   => 'width: 60@t'],
            ['w-60@d'   => 'width: 60@d'],
            ['w-60@w'   => 'width: 60@w'],
            ['w-70'     => 'width: 70'],
            ['w-70@t'   => 'width: 70@t'],
            ['w-70@d'   => 'width: 70@d'],
            ['w-70@w'   => 'width: 70@w'],
            ['w-75'     => 'width: 75'],
            ['w-75@t'   => 'width: 75@t'],
            ['w-75@d'   => 'width: 75@d'],
            ['w-75@w'   => 'width: 75@w'],
            ['w-80'     => 'width: 80'],
            ['w-80@t'   => 'width: 80@t'],
            ['w-80@d'   => 'width: 80@d'],
            ['w-80@w'   => 'width: 80@w'],
            ['w-90'     => 'width: 90'],
            ['w-90@t'   => 'width: 90@t'],
            ['w-90@d'   => 'width: 90@d'],
            ['w-90@w'   => 'width: 90@w'],
            ['w-100'    => 'width: 100'],
            ['w-100@t'  => 'width: 100@t'],
            ['w-100@d'  => 'width: 100@d'],
            ['w-100@w'  => 'width: 100@w'],
            ['w-1/3'    => 'width: 1/3'],
            ['w-1/3@t'  => 'width: 1/3@t'],
            ['w-1/3@d'  => 'width: 1/3@d'],
            ['w-1/3@w'  => 'width: 1/3@w'],
            ['w-2/3'    => 'width: 2/3'],
            ['w-2/3@t'  => 'width: 2/3@t'],
            ['w-2/3@d'  => 'width: 2/3@d'],
            ['w-2/3@w'  => 'width: 2/3@w'],
            ['w-1/4'    => 'width: 1/4'],
            ['w-1/4@t'  => 'width: 1/4@t'],
            ['w-1/4@d'  => 'width: 1/4@d'],
            ['w-1/4@w'  => 'width: 1/4@w'],
            ['w-1/2'    => 'width: 1/2'],
            ['w-1/2@t'  => 'width: 1/2@t'],
            ['w-1/2@d'  => 'width: 1/2@d'],
            ['w-1/2@w'  => 'width: 1/2@w'],
            ['w-3/4'    => 'width: 3/4'],
            ['w-3/4@t'  => 'width: 3/4@t'],
            ['w-3/4@d'  => 'width: 3/4@d'],
            ['w-3/4@w'  => 'width: 3/4@w'],
            ['w-1/6'    => 'width: 1/6'],
            ['w-1/6@t'  => 'width: 1/6@t'],
            ['w-1/6@d'  => 'width: 1/6@d'],
            ['w-1/6@w'  => 'width: 1/6@w'],
            ['w-5/6'    => 'width: 5/6'],
            ['w-5/6@t'  => 'width: 5/6@t'],
            ['w-5/6@d'  => 'width: 5/6@d'],
            ['w-5/6@w'  => 'width: 5/6@w'],
            ['ml-0'     => 'offset: 0 (reset)'],
            ['ml-0@t'   => 'offset: 0@t (reset)'],
            ['ml-0@d'   => 'offset: 0@d (reset)'],
            ['ml-0@w'   => 'offset: 0@w (reset)'],
            ['mx-auto'   => 'center column'],
            ['mx-auto@t'   => 'center column @t'],
            ['mx-auto@d'   => 'center column @d'],
            ['mx-auto@w'   => 'center column @w'],
            ['order-0'   => 'order: 0'],
            ['order-0@t' => 'order: 0@t'],
            ['order-0@d' => 'order: 0@d'],
            ['order-0@w' => 'order: 0@w'],
            ['order-1'   => 'order: 1'],
            ['order-1@t' => 'order: 1@t'],
            ['order-1@d' => 'order: 1@d'],
            ['order-1@w' => 'order: 1@w'],
            ['order-2'   => 'order: 2'],
            ['order-2@t' => 'order: 2@t'],
            ['order-2@d' => 'order: 2@d'],
            ['order-2@w' => 'order: 2@w'],
            ['order-3'   => 'order: 3'],
            ['order-3@t' => 'order: 3@t'],
            ['order-3@d' => 'order: 3@d'],
            ['order-3@w' => 'order: 3@w'],
            ['order-4'   => 'order: 4'],
            ['order-4@t' => 'order: 4@t'],
            ['order-4@d' => 'order: 4@d'],
            ['order-4@w' => 'order: 4@w'],
            ['order-5'   => 'order: 5'],
            ['order-5@t' => 'order: 5@t'],
            ['order-5@d' => 'order: 5@d'],
            ['order-5@w' => 'order: 5@w'],
            ['order-6'   => 'order: 6'],
            ['order-6@t' => 'order: 6@t'],
            ['order-6@d' => 'order: 6@d'],
            ['order-6@w' => 'order: 6@w'],
            ['order-7'   => 'order: 7'],
            ['order-7@t' => 'order: 7@t'],
            ['order-7@d' => 'order: 7@d'],
            ['order-7@w' => 'order: 7@w'],
            ['order-8'   => 'order: 8'],
            ['order-8@t' => 'order: 8@t'],
            ['order-8@d' => 'order: 8@d'],
            ['order-8@w' => 'order: 8@w'],
            ['order-9'   => 'order: 9'],
            ['order-9@t' => 'order: 9@t'],
            ['order-9@d' => 'order: 9@d'],
            ['order-9@w' => 'order: 9@w'],
            ['ow-10'    => 'offset: 10'],
            ['ow-10@t'  => 'offset: 10@t'],
            ['ow-10@d'  => 'offset: 10@d'],
            ['ow-10@w'  => 'offset: 10@w'],
            ['ow-20'    => 'offset: 20'],
            ['ow-20@t'  => 'offset: 20@t'],
            ['ow-20@d'  => 'offset: 20@d'],
            ['ow-20@w'  => 'offset: 20@w'],
            ['ow-25'    => 'offset: 25'],
            ['ow-25@t'  => 'offset: 25@t'],
            ['ow-25@d'  => 'offset: 25@d'],
            ['ow-25@w'  => 'offset: 25@w'],
            ['ow-30'    => 'offset: 30'],
            ['ow-30@t'  => 'offset: 30@t'],
            ['ow-30@d'  => 'offset: 30@d'],
            ['ow-30@w'  => 'offset: 30@w'],
            ['ow-40'    => 'offset: 40'],
            ['ow-40@t'  => 'offset: 40@t'],
            ['ow-40@d'  => 'offset: 40@d'],
            ['ow-40@w'  => 'offset: 40@w'],
            ['ow-50'    => 'offset: 50'],
            ['ow-50@t'  => 'offset: 50@t'],
            ['ow-50@d'  => 'offset: 50@d'],
            ['ow-50@w'  => 'offset: 50@w'],
            ['ow-60'    => 'offset: 60'],
            ['ow-60@t'  => 'offset: 60@t'],
            ['ow-60@d'  => 'offset: 60@d'],
            ['ow-60@w'  => 'offset: 60@w'],
            ['ow-70'    => 'offset: 70'],
            ['ow-70@t'  => 'offset: 70@t'],
            ['ow-70@d'  => 'offset: 70@d'],
            ['ow-70@w'  => 'offset: 70@w'],
            ['ow-75'    => 'offset: 75'],
            ['ow-75@t'  => 'offset: 75@t'],
            ['ow-75@d'  => 'offset: 75@d'],
            ['ow-75@w'  => 'offset: 75@w'],
            ['ow-80'    => 'offset: 80'],
            ['ow-80@t'  => 'offset: 80@t'],
            ['ow-80@d'  => 'offset: 80@d'],
            ['ow-80@w'  => 'offset: 80@w'],
            ['ow-90'    => 'offset: 90'],
            ['ow-90@t'  => 'offset: 90@t'],
            ['ow-90@d'  => 'offset: 90@d'],
            ['ow-90@w'  => 'offset: 90@w'],
            ['ow-1/3'   => 'offset: 1/3'],
            ['ow-1/3@t' => 'offset: 1/3@t'],
            ['ow-1/3@d' => 'offset: 1/3@d'],
            ['ow-1/3@w' => 'offset: 1/3@w'],
            ['ow-2/3'   => 'offset: 2/3'],
            ['ow-2/3@t' => 'offset: 2/3@t'],
            ['ow-2/3@d' => 'offset: 2/3@d'],
            ['ow-2/3@w' => 'offset: 2/3@w'],
            ['ow-1/4'   => 'offset: 1/4'],
            ['ow-1/4@t' => 'offset: 1/4@t'],
            ['ow-1/4@d' => 'offset: 1/4@d'],
            ['ow-1/4@w' => 'offset: 1/4@w'],
            ['ow-1/2'   => 'offset: 1/2'],
            ['ow-1/2@t' => 'offset: 1/2@t'],
            ['ow-1/2@d' => 'offset: 1/2@d'],
            ['ow-1/2@w' => 'offset: 1/2@w'],
            ['ow-3/4'   => 'offset: 3/4'],
            ['ow-3/4@t' => 'offset: 3/4@t'],
            ['ow-3/4@d' => 'offset: 3/4@d'],
            ['ow-3/4@w' => 'offset: 3/4@w'],
            ['ow-1/6'   => 'offset: 1/6'],
            ['ow-1/6@t' => 'offset: 1/6@t'],
            ['ow-1/6@d' => 'offset: 1/6@d'],
            ['ow-1/6@w' => 'offset: 1/6@w'],
            ['ow-5/6'   => 'offset: 5/6'],
            ['ow-5/6@t' => 'offset: 5/6@t'],
            ['ow-5/6@d' => 'offset: 5/6@d'],
            ['ow-5/6@w' => 'offset: 5/6@w'],
        ],
        'masthead' => [
            ['-dark' => 'Dark'],
            ['-overlay' => 'Overlay'],
            ['-megamenu' => 'Mega Menu'],
            ['-logo-lg' => 'Logo: large'],
            ['-logo-md' => 'Logo: Medium'],
        ],
        'section' => [
            ['-lg'             => 'Section large spacing'],
            ['-hero'           => 'Hero default'],
            ['-center'         => 'Header center'],
            ['-measure'        => 'Header with measure'],
            ['-measure-narrow' => 'Header with narrow measure'],
            ['-measure-wide'   => 'Header with wide measure'],
            ['-bal'            => 'Header with line after title'],
        ],
        'tabs' => [
            ['-border' =>  'Bordered'],
            ['-underline' =>  'Underline'],
        ],
    ];

    // Utilities
    public static $utilities = [
        'backgrounds' => [
            ['bg-black'         => 'bg color: black'],
            ['bg-black-alpha'   => 'bg color: black-alpha'],
            ['bg-white'         => 'bg color: white'],
            ['bg-white-alpha'   => 'bg color: white-alpha'],
            ['bg-gray'          => 'bg color: gray'],
            ['bg-gray-50'       => 'bg color: gray-50'],
            ['bg-gray-100'      => 'bg color: gray-100'],
            ['bg-gray-200'      => 'bg color: gray-200'],
            ['bg-gray-300'      => 'bg color: gray-300'],
            ['bg-gray-400'      => 'bg color: gray-400'],
            ['bg-gray-500'      => 'bg color: gray-500'],
            ['bg-gray-600'      => 'bg color: gray-600'],
            ['bg-gray-700'      => 'bg color: gray-700'],
            ['bg-gray-800'      => 'bg color: gray-800'],
            ['bg-gray-900'      => 'bg color: gray-900'],
            ['bg-red'           => 'bg color: red'],
            ['bg-red-dark'      => 'bg color: red-dark'],
            ['bg-red-light'     => 'bg color: red-light'],
            ['bg-orange'        => 'bg color: orange'],
            ['bg-yellow'        => 'bg color: yellow'],
            ['bg-green'         => 'bg color: green'],
            ['bg-teal'          => 'bg color: teal'],
            ['bg-blue'          => 'bg color: blue'],
            ['bg-blue-dark'     => 'bg color: blue-dark'],
            ['bg-purple'        => 'bg color: purple'],
            ['bg-beige'         => 'bg color: beige'],
            ['bg-none'          => 'bg color: None'],
            ['bg-red-orange'                => 'bg gradient: red-orange'],
            ['bg-orange-gray-warm-light'    => 'bg gradient: orange-gray-warm-light'],
            ['bg-gray-warm-light-red'       => 'bg gradient: gray-warm-light-red'],
            ['bg-red-yellow'                => 'bg gradient: red-yellow'],
            ['bg-yellow-orange'             => 'bg gradient: yellow-orange'],
            ['bg-green-yellow'              => 'bg gradient: green-yellow'],
            ['bg-blue-teal'                 => 'bg gradient: blue-teal'],
            ['bg-blue-light-blue-dark'      => 'bg gradient: blue-light-blue-dark'],
            ['bg-blue-dark-teal'            => 'bg gradient: blue-dark-teal'],
            ['bg-teal-green'                => 'bg gradient: teal-green'],
            ['bg-blue-green'                => 'bg gradient: blue-green'],
            ['bg-blue-light-blue'           => 'bg gradient: blue-light-blue'],
            ['bg-blue-gray-cool'            => 'bg gradient: blue-gray-cool'],
            ['bg-blue-dark-gray-warm'       => 'bg gradient: blue-dark-gray-warm'],
            ['bg-blue-gray-warm'            => 'bg gradient: blue-gray-warm'],
            ['bg-gray-cool-blue-dark'       => 'bg gradient: gray-cool-blue-dark'],
            ['bg-gold-gray-warm-light'      => 'bg gradient: gold-gray-warm-light'],
            ['bg-red-blue'                  => 'bg gradient: red-blue'],
            ['bg-blue-orange'               => 'bg gradient: blue-orange'],
            ['bg-blue-light-yellow'         => 'bg gradient: blue-light-yellow'],
            ['bg-yellow-blue'               => 'bg gradient: yellow-blue'],
            ['bg-fixed'     => 'bg attachment: fixed'],
            ['bg-local'     => 'bg attachment: local'],
            ['bg-scroll'    => 'bg attachment: scroll'],
            ['bgo-none'     => 'bg overlay: none'],
            ['bgo-10'       => 'bg overlay: 10%'],
            ['bgo-20'       => 'bg overlay: 20%'],
            ['bgo-30'       => 'bg overlay: 30%'],
            ['bgo-40'       => 'bg overlay: 40%'],
            ['bgo-50'       => 'bg overlay: 50%'],
            ['bgo-60'       => 'bg overlay: 60%'],
            ['bgo-70'       => 'bg overlay: 70%'],
            ['bgo-80'       => 'bg overlay: 80%'],
            ['bgo-90'       => 'bg overlay: 90%'],
            ['bg-lt'        => 'bg position: left top'],
            ['bg-l'         => 'bg position: left'],
            ['bg-lb'        => 'bg position: left bottom'],
            ['bg-rt'        => 'bg position: right top'],
            ['bg-r'         => 'bg position: right'],
            ['bg-rb'        => 'bg position: right bottom'],
            ['bg-t'         => 'bg position: top'],
            ['bg-auto'      => 'bg size: auto'],
            ['bg-cover'     => 'bg size: cover'],
            ['bg-contain'   => 'bg size: contain'],
        ],
        'heights' => [
            ['vh-10'  => 'height: 10vh'],
            ['vh-20'  => 'height: 20vh'],
            ['vh-30'  => 'height: 30vh'],
            ['vh-40'  => 'height: 40vh'],
            ['vh-50'  => 'height: 50vh'],
            ['vh-60'  => 'height: 60vh'],
            ['vh-70'  => 'height: 70vh'],
            ['vh-80'  => 'height: 80vh'],
            ['vh-90'  => 'height: 90vh'],
            ['vh-100' => 'height: 100vh'],
        ],
    ];

    /**
     * Constructor
     * @return void
     */
    public function __construct()
    {
        $this->defineFields();
    }

    /**
     * Defines ACF fields
     * @return void
     */
    protected function defineFields()
    {
        collect(glob(__DIR__ . '/acf/groups/*.php'))->map(function ($group) {
            if ($group instanceof FieldsBuilder) {
                acf_add_local_field_group($group->build());
            }
        });
        add_action('init', function () {
            collect(glob(__DIR__ . '/acf/groups/*.php'))->map(function ($group) {
                return require_once($group);
            })->map(function ($group) {
                if ($group instanceof FieldsBuilder) {
                    acf_add_local_field_group($group->build());
                }
            });
        });
    }
}
